name: test_de_fonseca
description: A new Flutter project.

publish_to: 'none'

version: 1.0.5+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  printing: ^5.9.1
  pdf: ^3.10.4
  supabase_flutter: ^2.8.3
  google_sign_in: 6.2.1
  provider: ^6.1.5+1
  url_launcher: ^6.3.0
  dragon_charts_flutter: ^0.1.0
  graphify: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_logo.png
    - assets/images/rizo_logo.png

