name: test_de_fonseca
description: Rizo Dental - Dental Clinical Sanctuary & ATM Anamnesis

publish_to: 'none'

version: 1.0.6+7

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  printing: ^5.9.1
  pdf: ^3.10.4
  supabase_flutter: ^2.8.3
  google_sign_in: 6.2.1
  provider: ^6.1.5+1
  url_launcher: ^6.3.0
  dragon_charts_flutter: ^0.1.0
  graphify: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/rizo_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_logo.png
    - assets/images/rizo_logo.png
